/**
 * Test fixtures — fully synthetic CloudHub-style log samples.
 *
 * Every value here is invented for tests: a neutral `sample-orders-api` app,
 * placeholder UUIDs (c0ffee00-…), a placeholder worker id and RFC 5737
 * documentation IPs (192.0.2.x). Each fixture targets one parser/analyzer path.
 *
 * Line shape recognised by src/analysis/parser.ts:
 *   <ISO ts> <LEVEL> [<worker>] <logger> event:<id> <thread> - <message>
 */

export const APP = 'sample-orders-api-dev';
export const WORKER = 'WORKER-SAMPLE-0001';
export const NO_EVENT = '00000000-0000-0000-0000-000000000000';

/** Placeholder correlation / event id: corr(1) → c0ffee00-0000-4000-8000-000000000001 */
export function corr(n: number): string {
    return `c0ffee00-0000-4000-8000-${String(n).padStart(12, '0')}`;
}

export const CORR_1 = corr(1);
export const CORR_2 = corr(2);
export const CORR_3 = corr(3);
export const CORR_4 = corr(4);

/** HTTP API flow name as generated by APIkit for `post:\orders`. */
export const FLOW_POST_ORDERS = 'post:\\orders:sample-orders-api-config';
export const FLOW_CREATE_ORDER = 'create-order-flow';
export const FLOW_MAIN = 'sample-orders-api-main';
export const FLOW_INVENTORY = 'check-inventory-flow';

export const ERR_DOWNSTREAM = 'APP:DOWNSTREAM_UNAVAILABLE';
export const ERR_CONNECTIVITY = 'HTTP:CONNECTIVITY';
export const MSG_ORDER_FAILED = 'Order creation failed: downstream service unavailable';

export interface LogLineParts {
    ts: string;
    level: 'TRACE' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR' | 'FATAL';
    logger: string;
    /** Thread / processor segment between the event id and ` - ` */
    thread: string;
    body: string;
    worker?: string;
    /** Event id; omitted from the line when null */
    event?: string | null;
}

/** Build one log header line. */
export function logLine({ ts, level, logger, thread, body, worker = WORKER, event = NO_EVENT }: LogLineParts): string {
    const eventPart = event === null ? '' : ` event:${event}`;
    return `${ts} ${level} [${worker}] ${logger}${eventPart} ${thread} - ${body}`;
}

/** Mule processing thread with app-in-brackets prefix, e.g. `[MuleRuntime].uber.01: [app].flow.BLOCKING @00000001`. */
export function muleThread(location: string, n = 1, strategy = 'BLOCKING'): string {
    const id = String(n).padStart(2, '0');
    return `[MuleRuntime].uber.${id}: [${APP}].${location}.${strategy} @${String(n).padStart(8, '0')}`;
}

/** Build a JSON Logger entry: header ending in `- {` followed by the pretty-printed payload lines. */
export function jsonLoggerEntry(
    parts: Omit<LogLineParts, 'logger' | 'body'> & { logger?: string },
    payload: Record<string, unknown>,
): string {
    const [, ...rest] = JSON.stringify(payload, null, 2).split('\n');
    return [logLine({ logger: 'JsonLogger', ...parts, body: '{' }), ...rest].join('\n');
}

// ── Single-entry fixtures ───────────────────────────────

/** JSON Logger INFO block — multi-line join; correlationId, elapsed, tracePoint, content.flowName, rootContainer. */
export const SAMPLE_JSON_LOGGER_INFO = jsonLoggerEntry(
    { ts: '2026-01-15T10:00:01.000Z', level: 'INFO', event: CORR_1, thread: muleThread(FLOW_POST_ORDERS) },
    {
        correlationId: CORR_1,
        message: 'Order request received',
        tracePoint: 'START',
        priority: 'INFO',
        elapsed: 1200,
        locationInfo: {
            lineInFile: '10',
            component: 'json-logger:logger',
            fileName: 'orders.xml',
            rootContainer: FLOW_POST_ORDERS,
        },
        content: { env: 'dev', applicationName: APP, flowName: FLOW_POST_ORDERS },
        environment: 'dev',
    },
);

/** JSON Logger ERROR block — top-level errorType wins over content.errorType; stackTrace field → entry.stackTrace. */
export const SAMPLE_JSON_LOGGER_ERROR = jsonLoggerEntry(
    { ts: '2026-01-15T10:00:03.000Z', level: 'ERROR', event: CORR_1, thread: muleThread(FLOW_MAIN, 2) },
    {
        priority: 'ERROR',
        correlationId: CORR_1,
        message: MSG_ORDER_FAILED,
        errorType: ERR_DOWNSTREAM,
        content: { errorType: ERR_CONNECTIVITY, flowName: FLOW_CREATE_ORDER },
        stackTrace: 'HTTP:CONNECTIVITY: Connection refused by 192.0.2.20:8443',
    },
);

/** HTTP listener DEBUG — noise (listener logger name) with header continuation lines appended to message. */
export const SAMPLE_HTTP_DEBUG = [
    logLine({
        ts: '2026-01-15T10:00:00.900Z',
        level: 'DEBUG',
        logger: 'sample-http-listener-config',
        event: CORR_2,
        thread: 'http.listener.01',
        body: '[conn-0001, L:/192.0.2.10:8081 - R:/192.0.2.30:40000] READ: 512B POST /api/orders HTTP/1.1',
    }),
    `x-correlation-id: ${CORR_2}`,
    'Content-Type: application/json',
    'Accept: */*',
].join('\n');

/** DefaultExceptionListener — empty message after ` - `; unindented Message/Element DSL/Error type lines join into message. */
export const SAMPLE_EXCEPTION_LISTENER = [
    logLine({
        ts: '2026-01-15T10:00:03.001Z',
        level: 'ERROR',
        logger: 'DefaultExceptionListener',
        event: CORR_1,
        thread: muleThread(FLOW_CREATE_ORDER, 3, 'CPU_INTENSIVE'),
        body: '',
    }),
    `Message               : ${MSG_ORDER_FAILED}`,
    `Element DSL           : <raise-error doc:name="Raise error" type="${ERR_DOWNSTREAM}"></raise-error>`,
    `Error type            : ${ERR_DOWNSTREAM}`,
].join('\n');

/** Plain-text ERROR (no JSON body, no event id) — indented `at` / `Caused by:` / `... N more` lines → stackTrace. */
export const SAMPLE_PLAIN_ERROR_STACK = [
    logLine({
        ts: '2026-01-15T10:05:00.000Z',
        level: 'ERROR',
        logger: 'OrderClient',
        event: null,
        thread: muleThread(FLOW_INVENTORY, 4),
        body: 'Inventory lookup failed',
    }),
    '    at com.example.orders.InventoryClient.lookup(InventoryClient.java:42)',
    '    at com.example.orders.OrderService.create(OrderService.java:17)',
    '    Caused by: java.net.ConnectException: Connection refused',
    '    ... 12 more',
].join('\n');

/** Scheduler WARN — thread is lazily matched to the first ` - `; later ` - ` stays in the message. */
export const SAMPLE_SCHEDULER_WARN = logLine({
    ts: '2026-01-15T10:00:04.000Z',
    level: 'WARN',
    logger: 'trace',
    event: CORR_2,
    thread: 'http.listener.01',
    body: `Task rejected (AbortBusyPolicy) from '[MuleRuntime].uber' scheduler: [${APP}].${FLOW_MAIN}.CPU_LITE @00000005 - org.mule.runtime.core.internal.processor.strategy.SampleCallable`,
});

/** Startup INFO — lifecycle line with all-zero event id; no errors, not noise. */
export const SAMPLE_STARTUP_INFO = logLine({
    ts: '2026-01-15T09:00:01.000Z',
    level: 'INFO',
    logger: 'FlowConstructLifecycleManager',
    thread: 'WrapperListener_start_runner',
    body: `Initialising flow: ${FLOW_CREATE_ORDER}`,
});

// ── Multi-entry fixtures ────────────────────────────────

/**
 * Error context chain — one correlationId through listener flow → sub-flow → error → propagation,
 * plus a trailing JSON-less ERROR (no correlationId → time-window fallback).
 */
export const SAMPLE_ERROR_CONTEXT_CHAIN = [
    jsonLoggerEntry(
        { ts: '2026-01-15T10:00:00.000Z', level: 'INFO', event: CORR_1, thread: muleThread(FLOW_POST_ORDERS) },
        {
            correlationId: CORR_1,
            message: 'Order request started',
            tracePoint: 'START',
            elapsed: 0,
            content: { flowName: FLOW_POST_ORDERS },
        },
    ),
    jsonLoggerEntry(
        { ts: '2026-01-15T10:00:01.000Z', level: 'INFO', event: CORR_1, thread: muleThread(FLOW_CREATE_ORDER) },
        {
            correlationId: CORR_1,
            message: 'Create order started',
            tracePoint: 'START',
            elapsed: 1000,
            content: { flowName: FLOW_CREATE_ORDER },
        },
    ),
    jsonLoggerEntry(
        { ts: '2026-01-15T10:00:03.000Z', level: 'ERROR', event: CORR_1, thread: muleThread(FLOW_CREATE_ORDER, 2) },
        {
            correlationId: CORR_1,
            message: MSG_ORDER_FAILED,
            priority: 'ERROR',
            errorType: ERR_DOWNSTREAM,
            content: { flowName: FLOW_CREATE_ORDER, errorCode: 'DOWNSTREAM_UNAVAILABLE' },
            stackTrace: 'HTTP:CONNECTIVITY: Connection refused by 192.0.2.20:8443',
        },
    ),
    jsonLoggerEntry(
        { ts: '2026-01-15T10:00:03.002Z', level: 'ERROR', event: CORR_1, thread: muleThread(FLOW_MAIN, 2) },
        {
            correlationId: CORR_1,
            message: 'Error propagated to main flow',
            priority: 'ERROR',
            errorType: ERR_DOWNSTREAM,
            content: { flowName: FLOW_MAIN },
        },
    ),
    logLine({
        ts: '2026-01-15T10:00:03.010Z',
        level: 'ERROR',
        logger: 'ForwardingToListenerHandler',
        event: CORR_1,
        thread: 'http.listener.02',
        body: 'Exception caught',
    }),
].join('\n');

/** Mixed levels — startup INFO, 3 HTTP DEBUG noise lines, WARN, JSON ERROR and plain ERROR for stats/filters. */
export const SAMPLE_MIXED_LEVELS = [
    logLine({
        ts: '2026-01-15T09:00:00.000Z',
        level: 'INFO',
        logger: 'AbstractLifecycleManager',
        thread: 'WrapperListener_start_runner',
        body: 'Initialising Bean: sample-http-request-config',
    }),
    SAMPLE_STARTUP_INFO,
    ...[
        '[conn-0001] READ: 512B POST /api/orders',
        '[conn-0001] READ COMPLETE',
        '[conn-0002] WRITE: 92B HTTP/1.1 201 Created',
    ].map((body, i) =>
        logLine({
            ts: `2026-01-15T10:00:00.90${i}Z`,
            level: 'DEBUG',
            logger: 'sample-http-listener-config',
            event: CORR_2,
            thread: 'http.listener.01',
            body,
        }),
    ),
    jsonLoggerEntry(
        { ts: '2026-01-15T10:00:03.000Z', level: 'ERROR', event: CORR_1, thread: muleThread(FLOW_CREATE_ORDER, 2) },
        {
            correlationId: CORR_1,
            message: MSG_ORDER_FAILED,
            errorType: ERR_DOWNSTREAM,
            content: { flowName: FLOW_CREATE_ORDER },
        },
    ),
    SAMPLE_SCHEDULER_WARN,
    logLine({
        ts: '2026-01-15T10:00:04.010Z',
        level: 'ERROR',
        logger: 'ForwardingToListenerHandler',
        event: CORR_2,
        thread: 'http.listener.02',
        body: 'Exception caught',
    }),
].join('\n');

/**
 * Interleaved correlations — two requests (CORR_3 fails, CORR_4 succeeds) whose lines alternate.
 * Correlation-based context for the CORR_3 error must not pick up CORR_4 entries.
 */
export const SAMPLE_INTERLEAVED_CORRELATIONS = [
    [CORR_3, '2026-01-15T11:00:00.000Z', 'INFO', 'Order request started', FLOW_POST_ORDERS],
    [CORR_4, '2026-01-15T11:00:00.100Z', 'INFO', 'Order request started', FLOW_POST_ORDERS],
    [CORR_3, '2026-01-15T11:00:00.200Z', 'INFO', 'Create order started', FLOW_CREATE_ORDER],
    [CORR_4, '2026-01-15T11:00:00.300Z', 'INFO', 'Create order started', FLOW_CREATE_ORDER],
    [CORR_3, '2026-01-15T11:00:01.000Z', 'ERROR', MSG_ORDER_FAILED, FLOW_CREATE_ORDER],
    [CORR_4, '2026-01-15T11:00:01.100Z', 'INFO', 'Order created', FLOW_CREATE_ORDER],
    [CORR_4, '2026-01-15T11:00:01.200Z', 'INFO', 'Order request completed', FLOW_POST_ORDERS],
]
    .map(([id, ts, level, message, flowName]) =>
        jsonLoggerEntry(
            { ts, level: level as LogLineParts['level'], event: id, thread: muleThread(flowName) },
            {
                correlationId: id,
                message,
                ...(level === 'ERROR' ? { errorType: ERR_DOWNSTREAM } : {}),
                content: { flowName },
            },
        ),
    )
    .join('\n');

/**
 * Time-window fallback — JSON-less ERROR preceded by one line > 30s earlier (excluded)
 * and one within 30s (included), followed by one line within 30s.
 */
export const SAMPLE_TIME_WINDOW = [
    ['2026-01-15T12:00:00.000Z', 'INFO', 'Polling inventory feed'],
    ['2026-01-15T12:00:50.000Z', 'INFO', 'Inventory feed batch received'],
    ['2026-01-15T12:01:00.000Z', 'ERROR', 'Inventory feed batch rejected'],
    ['2026-01-15T12:01:05.000Z', 'INFO', 'Inventory feed retry scheduled'],
]
    .map(([ts, level, body]) =>
        logLine({
            ts,
            level: level as LogLineParts['level'],
            logger: 'InventoryPoller',
            event: null,
            thread: muleThread(FLOW_INVENTORY),
            body,
        }),
    )
    .join('\n');

/** WARN template collapse — 3 WARN lines differing only in IP/UUID/long-number tokens → one pattern; plus 1 INFO. */
export const SAMPLE_REPEATED_WARN = [
    ...[
        ['192.0.2.10', CORR_1, '30000'],
        ['192.0.2.11', CORR_2, '45000'],
        ['192.0.2.12', CORR_3, '60000'],
    ].map(([ip, id, ms], i) =>
        logLine({
            ts: `2026-01-15T13:00:0${i}.000Z`,
            level: 'WARN',
            logger: 'DownstreamClient',
            event: id,
            thread: muleThread(FLOW_INVENTORY, i + 1),
            body: `Downstream call to ${ip} timed out after ${ms} ms (request ${id})`,
        }),
    ),
    SAMPLE_STARTUP_INFO,
].join('\n');

export const REPEATED_WARN_TEMPLATE = 'Downstream call to <*> timed out after <*> ms (request <*>)';
